### ISSUE TITLE
No image in safari

### ISSUE THREAD

**Issue by ApoAdrian** [caseymcj/raspberrypi_node_camera_web_streamer#5]
I get it working fine in chrome in my laptop, but if I try in Safari no image appear. Also there are no errors in server side and browser console.

I have try it in iPhone Safari and Chrome browsers and also not working. (I think they use the same webkit module).

**Comment by ApoAdrian** [comment]
Solved!

I have open videoStream with Code and appreciate that:
`res.write('--myboundary\nContent-Type: image/jpg\nContent-length: ${frameData.length}\n\n');`

I've notice that it was using normal `'`, so after changing it to backticks ``` it works on Safari and also in iPhone.

**Comment by caseymcj** [comment]
Hi Adrian,

Nice catch! This was a rookie mistake on my part. I'll update it with the correct backticks. Thanks for letting me know.

-caseymcj

**Comment by caseymcj** [comment]
This issue has been addressed by [PR 7](https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/pull/7).
