### ISSUE TITLE
acceptConnections not a function? 

### ISSUE THREAD

**Issue by AmberStanifer1** [caseymcj/raspberrypi_node_camera_web_streamer#6]
![Screenshot_16](https://user-images.githubusercontent.com/80002942/115972647-ae30cb00-a51d-11eb-8b17-eab2c76b6bcb.png)
![Screenshot_17](https://user-images.githubusercontent.com/80002942/115972648-aec96180-a51d-11eb-9178-bc6f7f117ff7.png)

Hey! I'm relatively new to all this and am attempting a project to have a working live stream so that I can check on my cats while I'm outside the house. I have tried using your code but am getting an error regarding the acceptConnections part? I am unsure why this is occuring and any help would be greatly appreciated! Thanks! I have posted screenshots of both the error and code with this :)

**Comment by caseymcj** [comment]
Hi Amber,

Thanks for reaching out. This sounds like a great use-case!

The code should work out-of-the-box with only minor configuration. I think the most common reason for this kind of error is if the libraries didn't get fully installed after you cloned the repository to your pi. Be sure to run the exact command `npm install` from within the project's root folder. (If you have done this, I'd recommend doing it again anyway).

Also, be sure that your [camera interface on the raspberry pi is enabled](https://www.raspberrypi.org/documentation/configuration/camera.md).

Let me know if this doesn't take care of it for you. Good luck!

Casey

**Comment by arnaudjaspard** [comment]
Hi Casey,
Amber is right, in your index.js you require const videoStream = require('raspberrypi-node-camera-web-streamer');
But of course this is not installed, since you are already inside your lib.
instead you should load it locally using :
const videoStream = require('./videoStream');

It will then work

Arnaud

**Comment by caseymcj** [comment]
Hi Arnaud and Amber,

Arnaud - you're exactly right. THANK YOU for catching this.

Amber - I have updated the code to fix this problem; this issue has been addressed by [PR 7](https://github.com/caseymcj/raspberrypi_node_camera_web_streamer/pull/7). Thanks to Arnaud, it should work now. Please `git pull` and give it another try. :) And let me know if you have further questions or difficulties.

Thanks for your interest.

Casey
